

# ZIP_DIR
# GODOT_FILE
# GODOT_NAME
# OUTPUT
message(STATUS "Entered PackageWeb.cmake")

cmake_path(REPLACE_EXTENSION GODOT_FILE LAST_ONLY "wasm" OUTPUT_VARIABLE GODOT_WASM_FILE)

message(STATUS "${GODOT_FILE}")
message(STATUS "${GODOT_WASM_FILE}")

file(READ "${GODOT_FILE}" JS_CONTENT)
file(READ "${ZIP_DIR}/${GODOT_NAME}.js" TEMPLATE_CONTENT)
string(REPLACE "___EMSCRIPTEN_JS_PLACEHOLDER___" "${JS_CONTENT}" TEMPLATE_CONTENT "${TEMPLATE_CONTENT}" )
file(WRITE "${ZIP_DIR}/${GODOT_NAME}.js" "${TEMPLATE_CONTENT}")

file(COPY_FILE ${GODOT_WASM_FILE} "${ZIP_DIR}/${GODOT_NAME}.wasm")

file(GLOB ZIP_FILES "${ZIP_DIR}/*")

execute_process(
    COMMAND ${CMAKE_COMMAND} -E tar "cf" ${GODOT_OUTPUT} --format=zip ${ZIP_FILES}
    WORKING_DIRECTORY ${ZIP_DIR}
)